context:
  version: "0.0.4"

package:
  name: jupyter-ai-router
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-ai-router/jupyter_ai_router-${{ version }}.tar.gz
  sha256: 81878b138ecf62f8e42e8ffbb8ae3eb21befc86235f253f5c55acebe767f065a

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.5.0
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version >=0.3.2
    - jupyterlab >=4.0.0,<5
  run:
    - python >=${{ python_min }}
    - jupyter_server_documents >=0.2.0a0
    - jupyter_server >=2.4.0,<3
    - jupyterlab-chat >=0.19.0

tests:
  - python:
      imports:
        - jupyter_ai_router
      pip_check: true
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/jupyter-ai-contrib/jupyter-ai-router
  summary: "The core routing layer used in Jupyter AI to process chat messages"
  license: BSD-3-Clause
  license_file: LICENSE
  documentation: https://jupyter-ai.readthedocs.io/
  repository: https://github.com/jupyter-ai-contrib/jupyter-ai-router

extra:
  recipe-maintainers:
    - jtpio
    - dlqqq
    - andrii-i
